import express from 'express';
import cors from 'cors';
import { Criticality, VulnContext, ReportContext } from '@kiber-dnt/shared-types';

const app = express();
app.use(cors());
app.use(express.json());

const PORT = parseInt(process.env.AI_PORT || '5000');

/**
 * Calculate risk score using weighted formula:
 * riskScore = cvssScore * 0.4 + epssScore * 10 * 0.3 + criticalityWeight * 0.3
 * criticalityWeight: LOW=2, MEDIUM=5, HIGH=8, CRITICAL=10
 */
function calculateRiskScore(cvssScore: number, epssScore: number, criticality: string): number {
  const cw = { LOW: 2, MEDIUM: 5, HIGH: 8, CRITICAL: 10 }[criticality] || 5;
  return Math.min(10, +(cvssScore * 0.4 + epssScore * 10 * 0.3 + cw * 0.3).toFixed(2));
}

function calculateConfidence(cvssScore: number, epssScore: number, criticality: string): number {
  const cw = { LOW: 2, MEDIUM: 5, HIGH: 8, CRITICAL: 10 }[criticality] || 5;
  return Math.min(100, Math.round((cvssScore / 10) * 40 + epssScore * 30 + (cw / 10) * 30));
}

function generateReasoning(ctx: VulnContext): string {
  const severity = ctx.cvssScore >= 9 ? 'Critical' : ctx.cvssScore >= 7 ? 'High' : 'Medium';
  return `Vulnerability analysis: CVE ${ctx.cveId || 'unknown'} with CVSS ${ctx.cvssScore} (${severity}). `
    + `EPSS probability: ${(ctx.epssScore * 100).toFixed(1)}%. `
    + `Asset type: ${ctx.assetType}, Criticality: ${ctx.assetCriticality}. `
    + `Risk score: ${calculateRiskScore(ctx.cvssScore, ctx.epssScore, ctx.assetCriticality)}. `
    + 'Recommendation: ' + (ctx.cvssScore >= 7 ? 'Apply virtual patch or isolate immediately.' : 'Monitor and schedule patch.');
}

function generateReport(ctx: ReportContext): string {
  return `# Incident Report\n\n`
    + `## Incident: ${ctx.incidentId}\n\n`
    + `## What Happened\n${ctx.threatTitle} detected on ${ctx.assetName}.\n\n`
    + `## How Detected\nAI analysis with CVSS ${ctx.cvssScore} and confidence ${ctx.confidenceScore}%.\n\n`
    + `## Response\nAutomated SOAR remediation applied.\n\n`
    + `## Timeline\n${JSON.stringify(ctx.timeline, null, 2)}\n\n`
    + `*Report generated by AI Engine*\n`;
}

// REST endpoints for the API service to call
app.post('/api/analyze', (req, res) => {
  const ctx = req.body as VulnContext;
  const riskScore = calculateRiskScore(ctx.cvssScore, ctx.epssScore, ctx.assetCriticality);
  const confidence = calculateConfidence(ctx.cvssScore, ctx.epssScore, ctx.assetCriticality);
  const reasoning = generateReasoning(ctx);
  res.json({ riskScore, confidence, reasoning, recommendedAction: confidence > 90 ? 'auto_isolate' : 'manual_review' });
});

app.post('/api/report', (req, res) => {
  const ctx = req.body as ReportContext;
  const report = generateReport(ctx);
  res.json({ report });
});

app.get('/api/health', (_, res) => res.json({ status: 'ok', service: 'ai-engine' }));

app.listen(PORT, () => {
  console.log(`🧬 Kiber-DNT AI Engine running on port ${PORT}`);
  console.log(`   Endpoints: POST /api/analyze, POST /api/report`);
});
